---
name:  " Production Shopping aplication image  build"
on:
  push:
    branches:
      - production


jobs:

  build:

    runs-on:  ubuntu-latest

    env:
      packer_version: "1.9.4"

    steps:


      -  name: "checkout Repository"
         uses: actions/checkout@v3


      -  name: "Installing packer"
         uses: hashicorp/setup-packer@main
         with:
            version: ${{ env.packer_version }}

      -  name: "packer init"
         run: packer init .
         working-directory: ./packer/

      -  name: "packer validate"
         run: packer validate -var-file="prod.pkrvars.hcl" .
         working-directory: ./packer/

      -  name: "packer image build"
         run: packer build -var-file="prod.pkrvars.hcl" .
         working-directory: ./packer/
         env: 
           AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.PROD_REGION }}

      -  name: "Notify the job deploy for prod"
         uses: peter-evans/repository-dispatch@v2
         with:
           token: ${{ secrets.NOTIFY_PAT }}
           repository: https://github.com/swathiarjun/shopping-app-infra
           event-type: deploy-event-prod

